# Generated by Django 2.1.3 on 2018-11-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlackHook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
