# Generated by Django 2.1.3 on 2018-11-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlackHook', '0002_auto_20181116_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='slack_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='slackuser',
            old_name='slack_name',
            new_name='user_name',
        ),
    ]
